
#################################
# Backend
#################################

backend = "glx";          # Use OpenGL for performance and effects
vsync = true;

#################################
# Shadow
#################################

shadow = true;
shadow-radius = 12;
shadow-offset-x = -15;
shadow-offset-y = -15;
shadow-opacity = 0.3;
shadow-exclude = [
  "class_g = 'i3-frame'",
  "name = 'Notification'",
  "name *= 'Conky'",
  "name = 'cairo-clock'",
  "class_g ?= 'notify-osd'",
  "class_g = 'slop'",
  "class_g = 'Kitty'",
	"class_g ?= 'Thunderbird' && class_i = 'Popup' && argb",
	"class_g = 'firefox' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
	"class_g = 'Firefox' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
	"class_g = 'firefox-esr' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
	"class_g = 'Firefox-esr' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
	"class_g = 'Tor Browser' && (window_type = 'utility') && argb",
	"class_g = 'Navegador Tor' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
	"class_g = 'Thunderbird' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
	"class_g = 'Mozilla Thunderbird' && (window_type = 'utility' || window_type = 'popup_menu') && argb",
    "class_g ?= 'Xfce4-power-manager'",
  "class_g ?= 'vokoscreen' && argb",
	"name = 'Área'",
	"name *= 'Cuenta regresiva'",
	"_NET_WM_WINDOW_TYPE:a *= '_KDE_NET_WM_WINDOW_TYPE_OVERRIDE'"
];

#################################
# Fading
#################################

fading = true;
fade-delta = 10;
fade-in-step = 0.05;
fade-out-step = 0.05;
fade-exclude = [];

#################################
# Transparency
#################################

inactive-opacity = 0.85;
active-opacity = 0.95;
frame-opacity = 0.75;
inactive-opacity-override = false;
opacity-exclude = [
  "name = 'YouTube'"
]
opacity-rule = [
  "90:class_g = 'Alacritty'",
  "90:class_g = 'Code'",
  "85:class_g = 'Firefox'",
  "100:name    = 'Picture-in-Picture'",
];

#################################
# Blur (requires ibhagwan fork)
#################################

blur:
{
  method = "dual_kawase";
  strength = 5;
  background = true;
  background-frame = true;
  background-fixed = true;
};

blur-background-exclude = [
  "class_g = 'Peek'",
	"class_g = 'slop'",
	"class_g = 'Pensela'",
	"name = 'Drawing Board'",
#    "window_type = 'dock'",
	"window_type = 'dropdown_menu'",
	"window_type = 'combo'",
	"window_type = 'popup_menu'",
	"window_type = 'utility'",
    "window_type = 'desktop'",
	"_GTK_FRAME_EXTENTS@:c"
];

#################################
# Rounded Corners
#################################

corner-radius = 10;
rounded-corners-exclude = [
  "class_g = 'Polybar'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];

#################################
# Animations (ibhagwan fork only)
#################################

animations = true;
animation-stiffness = 200;
animation-dampening = 15;
animation-window-mass = 0.5;
animation-for-open-window = "zoom";
animation-for-unmap-window = "fade-out";
animation-for-transient-window = "slide-down";

#################################
# Other Settings
#################################

use-dock-shadow = false;
detect-client-opacity = true;
detect-rounded-corners = true;
log-level = "warn";
