##~/.config/i3/
# Created by: schanver

[timewarrior]
command=$HOME/.scripts/tw-i3block
interval=1

[caps]
command=$HOME/.scripts/caps
interval=1
color=#ff0000

[mpd]
command=$HOME/.scripts/mpd
interval=5
signal=10
#background=#ff2662

[updates]
command=$HOME/.scripts/last_update.sh
click-left=$HOME/.scripts/last_update.sh toggle
interval=300
markup=none
color=#ffffff
#background=#4FA3D1
margin-left=10
margin-right=10

[battery]
command=$HOME/.scripts/battery
interval=30
LABEL=⚡
#LABEL=BAT 
instance=BAT0
markup=pango
#color=#ffffff

[temperature]
command=$HOME/.scripts/temperature
label= 
interval=10
T_WARN=70
T_CRIT=90
#SENSOR_CHIP=""
#background=#888f9

[time]
command=$HOME/.scripts/clock
interval=60
signal=1
markup=none
color=#ffffff
#background=#72767d

[dunst-dnd]
command=$HOME/.scripts/dunst_dnd
interval=3
margin-right=10
