##~/.config/i3/
# Created by: schanver

[pomodoro_timer]
command=$HOME/.config/i3/scripts/pomodoro.sh
interval=1
color=#000000
background=#22aa52

[updates]
command=$HOME/.scripts/last_update.sh
click-left=$HOME/.scripts/last_update.sh toggle
interval=300
markup=none
color=#ffffff
background=#4FA3D1
margin-left=10
margin-right=10

[battery]
command=$HOME/.scripts/battery
interval=30
#LABEL=BAT 
instance=BAT1
markup=pango
#color=#ffffff
background=#8233a1

[temperature]
command=$HOME/.scripts/temperature
label= 
interval=10
T_WARN=70
T_CRIT=90
#SENSOR_CHIP=""
background=#888f9

[time]
command=$HOME/.scripts/time
interval=60
signal=1
markup=none
color=#ffffff
background=#72767d
