#~/.config/i3/
# Created by: schanver


[pacman-updates]
command=$HOME/.scripts/arch-update
markup=pango
interval=3600
QUIET=true
WATCH=^linux.* ^pacman.*
BASE_COLOR=#5fff5f
UPDATE_COLOR=#FFFF85
AUR=true
LABEL= 

[aur-update]
command=$HOME/.scripts/aur-update
markup=pango
format=json
interval=43200
UPDATE_COLOR=red
QUIET=1
IGNORE=root vidyodesktop
#CACHE_UPDATES=0
FORCE_IPV4=1

[battery]
command=$HOME/.scripts/battery
interval=30
LABEL=BAT 
#LABEL=⚡
BAT_NUMBER=0

[temperature]
command=$HOME/.scripts/temperature
label=TEMP 
interval=10
T_WARN=70
T_CRIT=90
#SENSOR_CHIP=""

[volume-pulseaudio]
command=$HOME/.scripts/volume-pulseaudio
interval=persist
SUBSCRIBE=1
USE_ALSA_NAME=1

[time]
command=$HOME/.scripts/time
interval=1
#TZ_FILE=~/.tz
STRFTIME_FORMAT=%d-%m-%Y %H:%M
TZONES=$DEFAULT_TZ,
TZ_LABELS=
