conky.config = {
    alignment = 'middle_middle',
    background = false,
    default_color = 'FFFFFF',
    double_buffer = true,
    extra_newline = false,
    font = 'Iosevka Nerd Font:size=15',
    gap_x = 50,
    gap_y = 0,
    radius = 24,
    minimum_height = 800,
    minimum_width = 400,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    color0 = "#222333",
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_class = 'Conky',
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    own_window_type = 'override',
    own_window_colour = "#222555",
    border_inner_margin = 50,
    lua_load = '~/.config/conky/agenda.lua'
}
conky.text = [[
${execi 60 ~/.scripts/print-agenda}
${lua_parse parse_agenda}
]]
