unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

set -g default-terminal "screen-256color"
set -g mouse on 

set -g status-position bottom
set -g status-justify centre
set -g status-style 'fg=color2 bg=#29262f'
set -g status-right ''
set -g status-left '#S'
set -g status-left-style 'fg=color3'
set -g status-right-length 0
set -g status-left-length 100
setw -g window-status-current-style 'fg=colour1 bg=default bold'
setw -g window-status-current-format '#I:#W '
setw -g window-status-style 'fg=color6'
set -g pane-border-style 'fg=#555555'
set -g pane-active-border-style 'fg=color2'


bind | split-window -h
bind - split-window -v
bind Space last-window

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# Switch between sessions
bind-key ( switch-client -p  
bind-key ) switch-client -n 

set-option -g allow-rename on

bind -n M-0 select-window -t 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
