#!/usr/bin/env bash 


FILE=$(find ~/org/ss25 ~/Documents/ -type f -name "*.pdf" 2>/dev/null| rofi -dmenu -i -p "Open PDF:" -config ~/dotfiles/rofi/rofidmenu.rasi)
[ -n "$FILE" ] && zathura "$FILE" 2>/dev/null
