#!/usr/bin/env bash
CONFIG="$HOME/.config/rofi/rofi-rmpc.rasi"

current=$(mpc current)
if [[ -z "$current" ]]; then
  current="Nothing is currently playing"
else
  current="Currently Playing: $current"
fi

options="Play/Pause\nNext\nPrev\nVolume 25%\nVolume 50%\nVolume 75%\nVolume 100%"

choice=$(echo -e "$options" | rofi -dmenu -i -mesg "$current" -p "Controls: " -config "$CONFIG" -filter "")

case "$choice" in
  "Play/Pause") mpc toggle ;;
  "Next")       mpc next ;;
  "Prev")       mpc prev ;;
  "Volume 25%") mpc volume 25 ;;
  "Volume 50%") mpc volume 50 ;;
  "Volume 75%") mpc volume 75 ;;
  "Volume 100%") mpc volume 100 ;;
esac
