#!/usr/bin/env bash
CONFIG="$HOME/.config/rofi/rofidmenu.rasi"

current=$(mpc current)
if [[ -z "$current" ]]; then
    current="Nothing is currently playing"
else
    current="Currently Playing: $current"
fi

queue=$(mpc playlist)
if [[ -z "$queue" ]]; then
    queue="Queue is empty"
fi

choice=$(echo -e "$queue" | rofi -dmenu -i -mesg "$current" -p "Queue: " -config "$CONFIG" -lines 15 -filter "")

if [[ -n "$choice" ]]; then
    track_num=$(mpc playlist | grep -nF "$choice" | cut -d: -f1 | head -n1)
    if [[ -n "$track_num" ]]; then
        mpc play "$track_num"
    fi
fi
