#!/usr/bin/env bash

# Enter the id of your touchscreen here
deviceID=16

# Look at the last symbol of the following command to determine if it's open or not

isOpen=$(xinput list-props $deviceID | grep "Device Enabled") 
set -- $isOpen 
isOpen="${!#}"

if [[ "$isOpen" -eq 0 ]]; then
  xinput enable "$deviceID"
else 
  xinput disable "$deviceID"
fi

